FROM openjdk:21-jdk
VOLUME /tmp 
COPY target/BookManagementAPIs-0.0.1-SNAPSHOT.jar book-management-microservice.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/book-management-microservice.jar"]