# app/Dockerfile

FROM python:latest

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
COPY summarization_app.py .
COPY summarization_lib.py . 
COPY 2022-Shareholder-Letter.pdf .
COPY uploaded_file.pdf .

RUN pip3 install -r requirements.txt

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "summarization_app.py", "--server.port=8501", "--server.address=0.0.0.0"]

