/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro;
@org.apache.avro.specific.AvroGenerated
public enum ModeOfPayment implements org.apache.avro.generic.GenericEnumSymbol<ModeOfPayment> {
  CARD, CASH  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ModeOfPayment\",\"namespace\":\"example.avro\",\"symbols\":[\"CARD\",\"CASH\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
