"""Unit tests for the generated test script pattern in deploy.sh.

The test script (scripts/test.sh) is generated by deploy.sh at runtime.
These tests validate the heredoc template embedded in deploy.sh.

Validates: Requirements 10.1–10.5
"""

import os
import re

import pytest

_DEPLOY_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "scripts", "deploy.sh"
)

with open(_DEPLOY_PATH) as _fh:
    DEPLOY_CONTENT = _fh.read()

# Extract the test script template from deploy.sh (everything written to scripts/test.sh)
# The template spans from the first heredoc writing to test.sh until the chmod line.
_TEST_TEMPLATE_MATCH = re.search(
    r"cat > scripts/test\.sh.*?chmod \+x scripts/test\.sh",
    DEPLOY_CONTENT,
    re.DOTALL,
)
assert _TEST_TEMPLATE_MATCH is not None, "Could not find test script template in deploy.sh"
TEST_TEMPLATE = _TEST_TEMPLATE_MATCH.group(0)


# ── Requirement 10.1: Executable permissions ──

class TestExecutablePermissions:
    def test_chmod_plus_x(self):
        """Generated test script gets executable permissions."""
        assert "chmod +x scripts/test.sh" in DEPLOY_CONTENT


# ── Requirement 10.2: Optional prompt with default ──

class TestDefaultPrompt:
    def test_accepts_cli_argument_with_default(self):
        """Test script accepts $1 with a default prompt value."""
        # Pattern: PROMPT="${1:-...}" or similar
        assert re.search(
            r'PROMPT="\$\{1:-[^}]+\}"', TEST_TEMPLATE
        ), "Test script must accept optional CLI prompt with a default"

    def test_default_prompt_is_meaningful(self):
        """Default prompt is a meaningful natural language query."""
        match = re.search(r'PROMPT="\$\{1:-([^}]+)\}"', TEST_TEMPLATE)
        assert match is not None
        default = match.group(1)
        assert len(default) > 10, f"Default prompt too short: '{default}'"


# ── Requirement 10.3: Auth before invoke ──

class TestAuthBeforeInvoke:
    def test_cognito_auth_before_lambda_invoke(self):
        """Test script authenticates with Cognito before invoking Lambda."""
        auth_pos = TEST_TEMPLATE.find("initiate-auth")
        invoke_pos = TEST_TEMPLATE.find("lambda invoke")
        assert auth_pos != -1, "Test script must call initiate-auth"
        assert invoke_pos != -1, "Test script must call lambda invoke"
        assert auth_pos < invoke_pos, (
            "initiate-auth must come before lambda invoke"
        )

    def test_uses_user_password_auth_flow(self):
        """Test script uses USER_PASSWORD_AUTH flow."""
        assert "USER_PASSWORD_AUTH" in TEST_TEMPLATE


# ── Requirement 10.4: Lambda invocation with JWT ──

class TestLambdaInvocation:
    def test_passes_authorization_header(self):
        """Test script passes Authorization header with Bearer token."""
        assert "Authorization" in TEST_TEMPLATE
        assert "Bearer" in TEST_TEMPLATE

    def test_passes_prompt_in_body(self):
        """Test script passes the prompt in the request body."""
        assert "prompt" in TEST_TEMPLATE


# ── Requirement 10.5: No nested JSON echo that breaks variable substitution ──

class TestNoNestedJsonEcho:
    def test_no_nested_echo_json_with_dollar_id_token(self):
        """Test script must not use nested echo JSON that breaks ${ID_TOKEN} substitution.

        Bad pattern: echo '{"headers": {"Authorization": "Bearer '${ID_TOKEN}'"}}' 
        This breaks because of nested quoting. The script should use a temp file
        or a heredoc approach instead.
        """
        # Look for echo commands that try to inline JSON with variable substitution
        bad_pattern = re.search(
            r"""echo\s+['"]\s*\{.*Authorization.*\$\{?ID_TOKEN""",
            TEST_TEMPLATE,
        )
        assert bad_pattern is None, (
            "Test script must not use echo with inline JSON containing ${ID_TOKEN}"
        )

    def test_uses_temp_file_or_heredoc_for_payload(self):
        """Test script should use a temp file or heredoc for the JSON payload."""
        uses_temp = "mktemp" in TEST_TEMPLATE or "PAYLOAD" in TEST_TEMPLATE
        uses_heredoc = "<<" in TEST_TEMPLATE and "EOF" in TEST_TEMPLATE
        assert uses_temp or uses_heredoc, (
            "Test script should use temp file or heredoc for JSON payload construction"
        )


# ── Requirement 10.1: Baked-in values ──

class TestBakedInValues:
    def test_gateway_id_baked_in(self):
        """Deploy script bakes GATEWAY_ID into test script."""
        assert "GATEWAY_ID" in TEST_TEMPLATE

    def test_cognito_pool_id_baked_in(self):
        """Deploy script bakes COGNITO_USER_POOL_ID into test script."""
        assert "COGNITO_USER_POOL_ID" in TEST_TEMPLATE

    def test_cognito_client_id_baked_in(self):
        """Deploy script bakes COGNITO_CLIENT_ID into test script."""
        assert "COGNITO_CLIENT_ID" in TEST_TEMPLATE

    def test_lambda_function_name_baked_in(self):
        """Deploy script bakes LAMBDA_FUNCTION_NAME into test script."""
        assert "LAMBDA_FUNCTION_NAME" in TEST_TEMPLATE

    def test_username_baked_in(self):
        """Deploy script bakes TEST_USERNAME into test script."""
        assert "TEST_USERNAME" in TEST_TEMPLATE

    def test_password_baked_in(self):
        """Deploy script bakes TEST_PASSWORD into test script."""
        assert "TEST_PASSWORD" in TEST_TEMPLATE
