#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# AgentCore Smithy Bedrock - Test Script
# Generated by deploy.sh — do not edit manually
# ============================================================

REGION="us-east-1"
GATEWAY_ID="smithy-bedrock-gateway-8oh0kf7tje"
COGNITO_USER_POOL_ID="us-east-1_UNquXQKHg"
COGNITO_CLIENT_ID="2j56oaad81l9nid0lssick0tsl"
LAMBDA_FUNCTION_NAME="agentcore-smithy-bedrock-AgentFunction"
TEST_USERNAME="testuser"
TEST_PASSWORD="TestPass123!"

PROMPT="${1:-Use the invoke model tool to ask Claude Haiku to write a short poem about the Beatles}"

echo "============================================================"
echo "Testing AgentCore Smithy Bedrock Agent"
echo "============================================================"
echo "Region: ${REGION}"
echo "Lambda: ${LAMBDA_FUNCTION_NAME}"
echo "Prompt: ${PROMPT}"
echo ""

# Authenticate with Cognito
echo ">>> Authenticating with Cognito..."
AUTH_RESULT=$(aws cognito-idp initiate-auth \
    --auth-flow USER_PASSWORD_AUTH \
    --client-id "${COGNITO_CLIENT_ID}" \
    --auth-parameters USERNAME="${TEST_USERNAME}",PASSWORD="${TEST_PASSWORD}" \
    --region "${REGION}" \
    --query "AuthenticationResult.IdToken" \
    --output text)

ID_TOKEN="${AUTH_RESULT}"
echo "Authentication successful."

# Build the Lambda payload
PAYLOAD_FILE="/tmp/test-payload-$$.json"
rm -f "${PAYLOAD_FILE}"
cat > "${PAYLOAD_FILE}" << PAYLOAD_INNER_EOF
{
    "headers": {
        "Authorization": "Bearer ${ID_TOKEN}"
    },
    "body": {
        "prompt": "${PROMPT}"
    }
}
PAYLOAD_INNER_EOF

# Invoke the Lambda function
echo ""
echo ">>> Invoking Lambda function..."
OUTPUT_FILE="/tmp/test-output-$$.json"
rm -f "${OUTPUT_FILE}"

aws lambda invoke \
    --function-name "${LAMBDA_FUNCTION_NAME}" \
    --payload "file://${PAYLOAD_FILE}" \
    --region "${REGION}" \
    --cli-binary-format raw-in-base64-out \
    "${OUTPUT_FILE}" > /dev/null

echo ""
echo ">>> Response:"
cat "${OUTPUT_FILE}"
echo ""

# Cleanup
rm -f "${PAYLOAD_FILE}" "${OUTPUT_FILE}"

echo ""
echo "============================================================"
echo "Test complete."
echo "============================================================"
